export const namemap = {
  'ACRO 1A & 1B': 'Acro 1A & 1B',
  'ACRO 2': 'Acro 2',
  'ACRO JR (R1)': 'Acro Jr (R1)',
  'ACRO JR (R2)': 'Acro Jr (R2)',
  'ADULT BALLET': 'Adult Ballet & Contemporary',
  'BALLET 1': 'Ballet 1',
  'BALLET 2': 'Ballet 2',
  'COMBO M 4:15 Ballet': 'Ballet/Tap 1 Combo (Mon 4:15) BALLET',
  'COMBO M 4:15 Tap': 'Ballet/Tap 1 Combo (Mon 4:15) TAP',
  'COMBO W 2:30 Ballet': 'Ballet/Tap 1 Combo (Wed 2:30) BALLET',
  'COMBO W 2:30 Tap': 'Ballet/Tap 1 Combo (Wed 2:30) TAP',
  'COMBO W 4:15 Ballet': 'Ballet/Tap 1 Combo (Wed 4:15) BALLET',
  'COMBO W 4:15 Tap': 'Ballet/Tap 1 Combo (Wed 4:15) TAP',
  'HIP HOP 1': 'Hip Hop 1',
  'HIP HOP 2': 'Hip Hop 2',
  'JAZZ 1': 'Jazz 1',
  'JAZZ 2': 'Jazz 2',
  'MODERN 1A': 'Lyrical/Modern 1 Angie',
  'MODERN 1B MARISSA': 'Lyrical/Modern 1 Marissa',
  'MODERN 2': 'Lyrical/Modern 2',
  'MT 1 ': 'Musical Theater 1 Emilee',
  'MT 1B MARISSA': 'Musical Theater 1 Marissa',
  'MT 2': 'Musical Theater 2B',
  'MT 3': 'Musical Theater 3',
  'HS MT': 'Musical Theater: High School',
  'PRE THURS 11AM ANGIE Ballet': 'Pre-Ballet/Tap (TH 11am) Angie BALLET',
  'PRE THURS 11AM ANGIE Tap': 'Pre-Ballet/Tap (TH 11am) Angie TAP',
  'PREDANCE R 11AM MARISSA Ballet': 'Pre-Ballet/Tap (TH 11am) Marissa BALLET',
  'PREDANCE R 11AM MARISSA Tap': 'Pre-Ballet/Tap (TH 11am) Marissa TAP',
  'PRE THURS 4:15 ANGIE Ballet': 'Pre-Ballet/Tap (TH 4:15pm) BALLET',
  'PRE THURS 4:15 ANGIE Tap': 'Pre-Ballet/Tap (TH 4:15pm) TAP',
  'PRE WED 10AM Ballet': 'Pre-Ballet/Tap (W 10am) BALLET',
  'PRE WED 10AM Tap': 'Pre-Ballet/Tap (W 10am) TAP',
  'PRE WED 11AM Ballet': 'Pre-Ballet/Tap (W 11am) BALLET',
  'PRE WED 11AM Tap': 'Pre-Ballet/Tap (W 11am) TAP',
  SpecTAPular: 'SpecTAPular',
  'TAP 1': 'Tap 1',
  'TAP 2': 'Tap 2',
  'TAP 3': 'Tap 3',
  'ADULT TAP 2': 'Tap: Advanced Beginning Adult',
  'ADULT TAP 1': 'Tap: Beginning Adult',
};
