export interface Recital {
  recital: string;
  dances: Dance[];
}

export interface Dance {
  dance: string;
  dancers: string[];
  song: string;
  artist: string;
}

export const recitals: Recital[] = [
  {
    recital: 'Babies 1',
    dances: [
      {
        dance: 'Ballet/Tap 1 Combo (Mon 4:15) BALLET',
        song: 'Go the Distance',
        artist: 'Kurt Schneider',
        dancers: [
          'Beugelink, Heartleigh',
          'Besse, Olivia',
          'DiLello, Adalyn',
          'Moore, Luna',
          'Sethi, Saisha',
          'Simmers, Mae',
          'Stavrianos, Valentina',
          'Wetmore, Ellison',
          'Reaney, Charlotte',
        ],
      },
      {
        dance: 'Ballet/Tap 1 Combo (Mon 4:15) TAP',
        song: "Aren't You Glad You're You",
        artist: '',
        dancers: [
          'Beugelink, Heartleigh',
          'Besse, Olivia',
          'DiLello, Adalyn',
          'Moore, Luna',
          'Sethi, Saisha',
          'Simmers, Mae',
          'Stavrianos, Valentina',
          'Wetmore, Ellison',
          'Reaney, Charlotte',
        ],
      },
      {
        dance: 'Pre-Ballet/Tap (W 11am) BALLET',
        song: "It's Such a Good Feeling",
        artist: 'JJ Heller',
        dancers: [
          'Catuna, Angelica',
          'Holloway, Lo ',
          'Humbles, Jacquie',
          'Landauer, Lennyx',
          'Richardson, Noemi',
          'Rivera, Isla',
          'Segura, Isa',
          'Tubbs, Selah',
          'Tubbs, Shiloh',
        ],
      },
      {
        dance: 'Pre-Ballet/Tap (W 11am) TAP',
        song: 'Dance Like Yo Daddy',
        artist: 'Meghan Trainor',
        dancers: [
          'Catuna, Angelica',
          'Holloway, Lo ',
          'Humbles, Jacquie',
          'Landauer, Lennyx',
          'Richardson, Noemi',
          'Rivera, Isla',
          'Segura, Isa',
          'Tubbs, Selah',
          'Tubbs, Shiloh',
        ],
      },
      {
        dance: 'Ballet/Tap 1 Combo (Wed 4:15) BALLET',
        song: 'Let Me Dance On',
        artist: 'Ron Artis II & Thunderstorm Artis',
        dancers: [
          'Armenta, Selah',
          'Baldwin, Kinsley',
          'Bervig, Cora',
          'Conner, Juliana',
          'Cox, Annie',
          'Fhip, Charlotte',
          'Gaines, Anniston',
          'Malito, Rayah',
          'Mather, Kate',
          'Puckett, Madison',
          'Ruedas, Selah',
          'Schon, Riley',
          'Schroff, Madison',
          'Shkarayev, Kira',
          'cky, Lani',
          'Turley, Adlee',
        ],
      },
      {
        dance: 'Ballet/Tap 1 Combo (Wed 4:15) TAP',
        song: 'Say a Little Prayer',
        artist: 'Tori Kelly & Pharrell Williams',
        dancers: [
          'Armenta, Selah',
          'Baldwin, Kinsley',
          'Bervig, Cora',
          'Conner, Juliana',
          'Cox, Annie',
          'Fhip, Charlotte',
          'Gaines, Anniston',
          'Malito, Rayah',
          'Mather, Kate',
          'Puckett, Madison',
          'Ruedas, Selah',
          'Schon, Riley',
          'Schroff, Madison',
          'Shkarayev, Kira',
          'cky, Lani',
          'Turley, Adlee',
        ],
      },
      {
        dance: 'Acro Jr (R1)',
        song: "Let's Get Loud",
        artist: 'Jennifer Lopez',
        dancers: [
          'Burnham, Amy',
          'Eklund, Rylee',
          'Larish, Ellie',
          'Mather, Kate',
          'Puckett, Madison',
          'Reeves, Makenna',
          'Rosinbum, Lilli',
          'Schroff, Madison',
          'Stonham, Alice',
          'Thomas, Isla',
          'Burz, Joanna',
        ],
      },
      {
        dance: 'Pre-Ballet/Tap (TH 11am) Angie BALLET',
        song: 'Spoonful of Sugar',
        artist: 'JJ Heller',
        dancers: [
          'Ady, Winnie',
          'Calderwood, Emery',
          'Ford, Quinn',
          'Lewis, Emily ',
          'Mather, Sadie',
          'Ratiu, Hailey',
          'Riewold, Hayden',
          'Soliman, Faith',
          'Taylor, Leelah',
          'Tunney, Brynn',
          'Turley, Teagan',
        ],
      },
      {
        dance: 'Pre-Ballet/Tap (TH 11am) Angie TAP',
        song: 'Wham (Re Bop Bam Bam)',
        artist: 'Mildred Bailey',
        dancers: [
          'Ady, Winnie',
          'Calderwood, Emery',
          'Ford, Quinn',
          'Lewis, Emily ',
          'Mather, Sadie',
          'Ratiu, Hailey',
          'Riewold, Hayden',
          'Soliman, Faith',
          'Taylor, Leelah',
          'Tunney, Brynn',
          'Turley, Teagan',
        ],
      },
    ],
  },
  {
    recital: 'Babies 2',
    dances: [
      {
        dance: 'Pre-Ballet/Tap (TH 11am) Marissa BALLET',
        song: 'Fly to Your Heart',
        artist: 'Selena Gomez',
        dancers: [
          'Carioto, Evie',
          'Catuna, Sophie',
          'Denney, Margot',
          'Dillon, Kinsley',
          'Hicks, Jane',
          'Hicks, Penelope',
          'Nielsen, Pearl',
          'Stonham, Alexandra',
          'Weidman, Elyssa',
        ],
      },
      {
        dance: 'Pre-Ballet/Tap (TH 11am) Marissa TAP',
        song: "Ain't She Sweet",
        artist: 'Frank Sinatra',
        dancers: [
          'Carioto, Evie',
          'Catuna, Sophie',
          'Denney, Margot',
          'Dillon, Kinsley',
          'Hicks, Jane',
          'Hicks, Penelope',
          'Nielsen, Pearl',
          'Stonham, Alexandra',
          'Weidman, Elyssa',
        ],
      },
      {
        dance: 'Pre-Ballet/Tap (W 10am) BALLET',
        song: "It's Such a Good Feeling",
        artist: 'JJ Heller',
        dancers: [
          'Arena, Margot',
          'Arnold, Emma',
          'Arnold, Rebecca',
          'Bragg, Hayden',
          'Burdette, Ariella',
          'Krueger, Rory',
          'Molina, Grace',
          'Moore, Zoey',
          'Ogden, Delaney',
          'Ratkovich, Amelia',
        ],
      },
      {
        dance: 'Pre-Ballet/Tap (W 10am) TAP',
        song: 'Dance Like Yo Daddy',
        artist: 'Meghan Trainor',
        dancers: [
          'Arena, Margot',
          'Arnold, Emma',
          'Arnold, Rebecca',
          'Bragg, Hayden',
          'Burdette, Ariella',
          'Krueger, Rory',
          'Molina, Grace',
          'Moore, Zoey',
          'Ogden, Delaney',
          'Ratkovich, Amelia',
        ],
      },
      {
        dance: 'Ballet/Tap 1 Combo (Wed 2:30) BALLET',
        song: 'Let Me Dance On',
        artist: 'Ron Artis II & Thunderstorm Artis',
        dancers: [
          'Ardelean, Nora ',
          'Cannon, Brielle',
          'Garibaldi, Ellie',
          'Giboney, Caroline',
          'Goodson, Lucy',
          'Henry, Mavis',
          'Lichter, Hadley Mae',
          'Linger, Josie',
          'Marshall, Audrey',
          'McBride, Gia',
          'Sims, Zariah',
          'Stefani, Nico',
          'Hansen, Mila',
          'Jajou, Savannah',
          'Jajou, Blanca',
        ],
      },
      {
        dance: 'Ballet/Tap 1 Combo (Wed 2:30) TAP',
        song: 'Say a Little Prayer',
        artist: 'Tori Kelly & Pharrell Williams',
        dancers: [
          'Ardelean, Nora ',
          'Cannon, Brielle',
          'Garibaldi, Ellie',
          'Giboney, Caroline',
          'Goodson, Lucy',
          'Henry, Mavis',
          'Lichter, Hadley Mae',
          'Linger, Josie',
          'Marshall, Audrey',
          'McBride, Gia',
          'Sims, Zariah',
          'Stefani, Nico',
          'Hansen, Mila',
          'Jajou, Savannah',
          'Jajou, Blanca',
        ],
      },
      {
        dance: 'Pre-Ballet/Tap (TH 4:15pm) BALLET',
        song: 'Spoonful of Sugar',
        artist: 'JJ Heller',
        dancers: [
          'Aja, Sophie',
          'Dunn, Harper',
          'Elgin, Ava',
          'Lizama, Skylar',
          'Lynch, Keturah',
          'McCrite, Sadie',
          'Moncrieff, Charley',
          'Mortensen, Lucy',
          'Yao, Fei',
          'Oh, Alethea "Thea"',
          'Rosinbum, Eden',
          'Rudzki, Kendall',
          'Vetter, Addie',
          'Vossler, Finnley',
        ],
      },
      {
        dance: 'Pre-Ballet/Tap (TH 4:15pm) TAP',
        song: 'Wham (Re Bop Bam Bam)',
        artist: 'Mildred Bailey',
        dancers: [
          'Aja, Sophie',
          'Dunn, Harper',
          'Elgin, Ava',
          'Lizama, Skylar',
          'Lynch, Keturah',
          'McCrite, Sadie',
          'Moncrieff, Charley',
          'Mortensen, Lucy',
          'Yao, Fei',
          'Oh, Alethea "Thea"',
          'Rosinbum, Eden',
          'Rudzki, Kendall',
          'Vetter, Addie',
          'Vossler, Finnley',
        ],
      },
      {
        dance: 'Acro Jr (R2)',
        song: "Let's Get Loud",
        artist: 'Jennifer Lopez',
        dancers: [
          'Burnham, Amy',
          'Eklund, Rylee',
          'Larish, Ellie',
          'Mather, Kate',
          'Puckett, Madison',
          'Reeves, Makenna',
          'Rosinbum, Lilli',
          'Schroff, Madison',
          'Stonham, Alice',
          'Thomas, Isla',
          'Burz, Joanna',
        ],
      },
    ],
  },
  {
    recital: 'Main Recital',
    dances: [
      {
        dance: 'Lyrical/Modern 1 Angie',
        song: 'Like the Dawn',
        artist: 'The Oh Hellos',
        dancers: [
          'Abney, Hanna',
          'Arnold, Kate',
          'Boone, Juliette',
          'Brunk, Emily',
          'Carnahan, Emmanuelle',
          'Clark, Abigail',
          'Gower, Ryleigh',
          'Hester, Jillian',
          'Hester, Josslyn',
          'Hunter, Carson',
          'Kimble, Emmelyn',
          'Murphy, Brynlie',
          'Rawlings, Eden',
          'Ritter, Emily',
          'Sorenson, Leila',
          'Wells, Anneliese',
        ],
      },
      {
        dance: 'Lyrical/Modern 2',
        song: 'What Was I Made For?',
        artist: 'Billie Eilish',
        dancers: [
          'Albert, Lucille',
          'Block, Tessa',
          'Boone, Clara',
          'Hoelzen, Emma',
          'Lenhart, Olivia',
          'Massaro, Maddie',
          'Meyer, Bailey',
          'Rawlings, Vivian',
          'Sims, Alexandra',
        ],
      },
      {
        dance: 'Tap: Beginning Adult',
        song: "Puttin' On the Ritz",
        artist: 'Pomplamoose',
        dancers: [
          'Dent, Kim',
          'Ellis, Dawn',
          'Stewart, Lisa',
          'Lin, Yvonne',
          'Moore, Heidi',
          'Ghrist, Tracy',
          'Snyder, Nancy',
          'Delatorre, Marien',
          'Riddle, Jenna',
        ],
      },
      {
        dance: 'Tap: Advanced Beginning Adult',
        song: 'Praise the Lord (feat. Thomas Rhett)',
        artist: 'BRELAND',
        dancers: [
          'Altounian, Kelli',
          'Boone, Jake',
          'Holman, Lisa',
          'Meyerhofer, Amanda',
          'Puckett, Kelsey',
          'Schroff, Amy',
        ],
      },
      {
        dance: 'SpecTAPular',
        song: "Let's Get Married",
        artist: 'Trolls 3',
        dancers: [
          'Addler, Harper',
          'Brown, Rylie',
          'Chen, Kinny',
          'Coffee, Ellie',
          'Conner, Oliver',
          'Rawlings, Grace',
          'Shkarayev, Ivan',
          'Tsai, Hanna',
          'Wolter, Ava',
          'Kinch, Emery',
          'Kinch, Hollyn',
          'Murphy, Joelle',
          'Bervig, Ava',
          'Bervig, Isla',
          'Bervig, Olivia',
          'Block, Kenley',
          'Block, Tessa',
          'Chandiramani, Anysia',
          'Chandiramani, Zyah',
          'Dorman, Grace',
          'Hunter, Carson',
          'Kidd, Avery ',
          'Morkunas, Charis',
          "O'Connor, Caitlyn",
          'Overson, Adalynn',
          'Rawlings, Eden',
          'Wells, Anneliese',
          'Wells, Jonah',
          'Boone, Asher',
          'Boone, Clara',
          'Carnahan, Emmanuelle',
          'Hunter, Lainey',
          'Hunter, Maia',
          'Morkunas, Phoenix',
          'Rawlings, Vivian',
          'Dent, Kim',
          'Ellis, Dawn',
          'Stewart, Lisa',
          'Lin, Yvonne',
          'Moore, Heidi',
          'Ghrist, Tracy',
          'Snyder, Nancy',
          'Delatorre, Marien',
          'Riddle, Jenna',
          'Altounian, Kelli',
          'Boone, Jake',
          'Holman, Lisa',
          'Meyerhofer, Amanda',
          'Puckett, Kelsey',
          'Schroff, Amy',
        ],
      },
      {
        dance: 'Tap 1',
        song: 'Joyful',
        artist: 'Dante Bowe',
        dancers: [
          'Addler, Harper',
          'Brown, Rylie',
          'Chen, Kinny',
          'Coffee, Ellie',
          'Conner, Oliver',
          'Rawlings, Grace',
          'Shkarayev, Ivan',
          'Tsai, Hanna',
          'Wolter, Ava',
          'Kinch, Emery',
          'Kinch, Hollyn',
          'Murphy, Joelle',
        ],
      },
      {
        dance: 'Tap 2',
        song: 'Well Git It & Born Ready',
        artist: 'Tommy Dorsey & His Orchestra, Dove Cameron',
        dancers: [
          'Bervig, Ava',
          'Bervig, Isla',
          'Bervig, Olivia',
          'Block, Kenley',
          'Block, Tessa',
          'Chandiramani, Anysia',
          'Chandiramani, Zyah',
          'Dorman, Grace',
          'Hunter, Carson',
          'Kidd, Avery ',
          'Morkunas, Charis',
          "O'Connor, Caitlyn",
          'Overson, Adalynn',
          'Rawlings, Eden',
          'Wells, Anneliese',
          'Wells, Jonah',
        ],
      },
      {
        dance: 'Tap 3',
        song: 'Broadway Melody & Freedom',
        artist: '? And Pharrell Williams',
        dancers: [
          'Boone, Asher',
          'Boone, Clara',
          'Carnahan, Emmanuelle',
          'Hunter, Lainey',
          'Hunter, Maia',
          'Morkunas, Phoenix',
          'Rawlings, Vivian',
        ],
      },
      {
        dance: 'Ballet 2',
        song: 'Kingdom Dance',
        artist: 'Tangled, Alan Menken',
        dancers: [
          'Arce, Alianna',
          'Arce, Lucianna',
          'Balzarini, Brooke',
          'Bichsel, Addilyn',
          'Bow, Shelby',
          'Brown, Rylie',
          'Fuss, Jane',
          'Grubor, Karsyn',
          'Jefferson, Avery',
          'Madana, Akshara',
          'Nicely, Zari',
          'Reddy Kambham, Arianna',
          'Vetter, Alex',
          'Thakur, Mayna',
        ],
      },
      {
        dance: 'Musical Theater: High School',
        song: 'Stick to the Status Quo',
        artist: 'High School Musical',
        dancers: [
          'Boone, Clara',
          'Hunter, Maia',
          'Morkunas, Phoenix',
          'Poku, Maleah',
          'Poku, Rebekah',
        ],
      },
      {
        dance: 'Ballet 1',
        song: "La Valse de L'Amour",
        artist: 'Cinderella, Patrick Doyle',
        dancers: [
          'Armstrong, Crystal',
          'Armstrong, Natalie',
          'Balla, Avyakta',
          'Benavides, Ellie',
          'Dillon, Paisley',
          'Iamiceli, Lucia',
          'Lonca, Abigail',
          'Martin, Stella',
          'Murphy, Joelle',
          'Musani, Ishika',
          'Kirara, Makenya',
          'Nguyen, Madeline',
          'Serban, Emily',
          'Spirko, Emerson',
        ],
      },
      {
        dance: 'Jazz 2',
        song: 'Masterpiece',
        artist: 'Tori Kelly, Lecrae',
        dancers: [
          'Arce, Gianna',
          'Carmona, Selah',
          'Hoelzen, Emma',
          'Lenhart, Olivia',
          'Murphy, Brynlie',
          'Phetteplace, Lyla',
          'Ramirez, Gabriella',
          'Stevens, Reagan',
          'Sutton, Harper',
          'Wells, Anneliese',
          'Wells, Emma',
        ],
      },
      {
        dance: 'Jazz 1',
        song: 'Come Together Now',
        artist: 'Matt and Kim',
        dancers: [
          'Boone, Juliette',
          'Broderick, Madison',
          'Focht, Delaney',
          'Ortiz, Gabriela',
          'Reeves, Makenna',
          'Sari Teriz, Valeria',
          'Shkarayev, Ivan',
          'Shkarayev, Kira',
          'Vaughn, Hailey',
          'Jernigan, Alyse',
          'Conner, Amaris',
        ],
      },
      {
        dance: 'Musical Theater 1 Marissa',
        song: 'Friend Like Me',
        artist: 'Robin Williams',
        dancers: [
          'Flandrau, Mackenzie',
          'Flandrau, Olivia',
          'Kidd, Beckham',
          'Roberts, Everly ',
          'Deminsky, Lilliana',
          'Moore, Elli',
        ],
      },
      {
        dance: 'Lyrical/Modern 1 Marissa',
        song: 'Daughter',
        artist: 'Sleeping at Last',
        dancers: [
          'Bala, Elizabeth',
          'Hernandez, Delaney',
          'Hoelzen, Kate',
          'Wilson, Presleigh',
          'Fontes, Amelia',
        ],
      },
      {
        dance: 'Acro 1A & 1B',
        song: 'Firework',
        artist: 'Katy Perry',
        dancers: [
          'Andersen, Sophia',
          'Bow, Shelby',
          'Burnham, Julie',
          'Coates, Amelia',
          'Delgado, Lola',
          'Farcas, Brielle',
          'Neypes, Grace',
          'Patterson, Shay',
          'Stonham, Isabelle',
          'Vetter, Alex',
          'Rajesh, Akshara',
          'Abney, Hanna',
          'Abuhmaiden, Isla',
          'Akert, Alaina',
          'Brunk, Emily',
          'Carmona, Sofia',
          'Chandiramani, Anysia',
          'Chandiramani, Zyah',
          'Foley, Abbey',
          'Hayslett, Grace',
          'Hester, Jillian',
          'Hester, Josslyn',
          'Song, Irene',
        ],
      },
      {
        dance: 'Acro 2',
        song: 'Scars to Your Beautiful',
        artist: 'Alesia Cara',
        dancers: [
          'Akert, Madi',
          'Albert, Lucille',
          'Boone, Clara',
          'Callanan-Attebery, Larsyn',
          'Haro, Angie',
          'Hunter, Lainey',
          'Jefferson, Mayah',
          'Massaro, Maddie',
          'Meyer, Bailey',
          'Miller, Grace',
          'Rawlings, Vivian',
        ],
      },
      {
        dance: 'Hip Hop 1',
        song: 'Watch Me',
        artist: 'Nick Jonas',
        dancers: [
          'Balzarini, Brooke',
          'Flandrau, Mackenzie',
          'Flandrau, Olivia',
          'Hernandez, Delaney',
          'Hoelzen, Kate',
          'Kimble, Emmelyn',
          'Larish, Eva',
          'Lorenzen, Zoey',
          'Morkunas, Charis',
          'Vaughn, Hailey',
          'Wells, Mikaela',
          'Wilson, Presleigh',
        ],
      },
      {
        dance: 'Hip Hop 2',
        song: "Movin'",
        artist: 'Group 1 Crew',
        dancers: ['Akert, Alaina', 'Arce, Gianna', 'Boone, Asher', 'Sutton, Harper'],
      },
      {
        dance: 'Musical Theater 3',
        song: '9 to 5',
        artist: 'Dolly Parton',
        dancers: [
          'Burz, Madi',
          'Hamilton, Kylie',
          'Hunter, Lainey',
          'Massaro, Maddie',
          'Meyer, Bailey',
          'Rawlings, Vivian',
          'Stock, Ella',
          'Wells, Ava',
          'Johnson, Giana',
        ],
      },
      {
        dance: 'Musical Theater 1 Emilee',
        song: 'Almost There',
        artist: 'Dara Renee',
        dancers: [
          'Abuhmaiden, Isla',
          'Arena, Eloise',
          'Bukowski, Maylee',
          'Coates, Amelia',
          'Foley, Abbey',
          'Larish, Ellie',
          'Larish, Eva',
          'Mann, Eleanor',
          'Mauldin, Everly',
          'Patel, Naomi',
          'Presser, Adaline',
          'Vilorio, Emma',
        ],
      },
      {
        dance: 'Musical Theater 2B',
        song: 'Pink',
        artist: 'Lizzo',
        dancers: [
          'Addler, Audree',
          'Bala, Loredana',
          'Bervig, Ava',
          'Bervig, Olivia',
          'Clarke, Christina',
          'Demas, Briddian',
          'Dorman, Grace',
          'Hunter, Carson',
          'Iverson, Paisley',
          'Overson, Brielle',
          'Rajesh, Akshara',
          'Rawlings, Eden',
          'Santina, Camryn',
          'Wells, Mikaela',
          'Widney, Madison',
        ],
      },
      {
        dance: 'Adult Ballet & Contemporary',
        song: 'Skyfall',
        artist: 'Adele',
        dancers: [
          'Avila, Marisol',
          'Chavez, Sarah',
          'Danielson, Kathryn',
          'Ellis, Dawn',
          'Gaio, Katilin',
          'Klunk, Nicole',
          'Wo, Kathleen',
        ],
      },
    ],
  },
];
